### ISSUE TITLE
Install issue - Docker Image

### ISSUE THREAD

**Issue by Os3r3um** [EdOverflow/megplus#13]
## Specifications

OS: Kali 2018.1 X64
```
Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.13-1kali1 (2018-01-25) x86_64 GNU/Linux
```
Docker 17.05 [docker-engine (17.05.0-ce-0~debian-stretch)] installed according to those instructions: 

https://www.ptrace-security.com/2017/06/14/how-to-install-docker-on-kali-linux-2017-1/

## Issue details

While trying to launch the docker image I do get as result such an error message: 

```
docker run -v $(pwd):/megplus abhartiya/tools_megplus test.txt
Unable to find image 'abhartiya/tools_megplus:latest' locally
latest: Pulling from abhartiya/tools_megplus
1be7f2b886e8: Pull complete 
6fbc4a21b806: Pull complete 
c71a6f8e1378: Pull complete 
4be3072e5a37: Pull complete 
06c6d2f59700: Pull complete 
097162963418: Pull complete 
e74792d436e5: Pull complete 
ea44cc114149: Pull complete 
46cf914528e7: Pull complete 
067162d34cbe: Pull complete 
Digest: sha256:4a31896cd10da001f7cd2838821f718be05a511ae289121f458cdc856baedd47
Status: Downloaded newer image for abhartiya/tools_megplus:latest
container_linux.go:247: starting container process caused "exec: \"./megplus.sh\": stat ./megplus.sh: no such file or directory"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"./megplus.sh\": stat ./megplus.sh: no such file or directory".
ERRO[0127] error getting events from daemon: net/http: request canceled 
```

*Note*: Got the same issue under a Bare Ubuntu 16.04.03 server with the docker properly installed.

**Comment by anshumanbh** [comment]
@Os3r3um Which directory are you trying to run the `docker run` command from? You need to be in the directory which has the `test.txt` file

**Comment by Os3r3um** [comment]
@anshumanbh I have uploaded a short movie. Usually, it makes more than a 1000 words. 

[megplus-docker-2018-02-07_12.38.18.mp4.zip](https://github.com/EdOverflow/megplus/files/1701217/megplus-docker-2018-02-07_12.38.18.mp4.zip)

**Comment by anshumanbh** [comment]
@Os3r3um  Okay, I saw the video. Here is what I'd recommend. Git clone the repo. CD into the repo and then try? Let me know if that works..

**Comment by anshumanbh** [comment]
What might be happening is that you are mounting your Kali desktop to the container which doesn't have the `megplus.sh` file, hence the error. If you run it from the repo itself, it should work. That'y my guess..

When you mount a volume to the container, you are essentially exposing your host volume to the container volume. And, we have to do this because we need to provide it the file containing the URLs which will be on the host. 

If the code can be changed such that we provide it a variable or maybe, provide it an external file - in that case, we don't need to mount the volume and it should just work - but thats not how megplus is coded to work as of now..

**Comment by Os3r3um** [comment]
Right. So: 

- I cloned the repo 
- I went inside
- echo "google.com" > test.txt [You know, to have the target file under the path]
- ran "docker run -v $(pwd):/megplus abhartiya/tools_megplus test.txt"

As result got this. I'd say still doesn't work because asks me to install gio which would have to be available in docker image? Maybe I'm wrong but based on my docker experience all dependencies are pulled off because how docker image works. 

![image](https://user-images.githubusercontent.com/3704868/35891632-35d3bde8-0c0a-11e8-98e4-f0498bc6ada8.png)

**Comment by anshumanbh** [comment]
I ran it now and it seems to be working fine. 

One more thing you can do is build the docker image yourself. I have provided the Dockerfile with the repo. So you can comment out the lines containing the gio command and then build your own image by typing something like `docker build -t test .` where `.` represents where the Dockerfile is present. And, then run `docker run -v $(pwd):/megplus test test.txt`

**Comment by Os3r3um** [comment]
nah, something is broken around. I have to figure out what's actually happening by  following the same steps on a fresh Ubuntu install. 


- I got the gio commands commented into the main mepglus.sh file. 
- I got the container rebuild
- I tried to start it as you have said but the same thing pops up; 

```
You need to install gio or you can comment out the lines containing the gio command.
```

Will close this issue now and reopen it rather than have it lurking around :)

Thanks.

**Comment by Os3r3um** [comment]
So, I have tried have it run it into a fresh Ubuntu 16.04.03 image + Docker latest version. With the gio lines commented, unfortunately, I still do get the same error message. At this point, I have no idea how you are able to run this one dockerized. 

![image](https://user-images.githubusercontent.com/3704868/35905543-6fb71d56-0c4c-11e8-91de-213886a1e9ba.png)

![image](https://user-images.githubusercontent.com/3704868/35905910-aa661c44-0c4d-11e8-99b4-ec64b2cc2b10.png)

**Comment by anshumanbh** [comment]
I guess we can get rid of gio all together? I will leave that upto Ed to decide what he wants to do with it but I am not sure whats going on exactly with your setup. 

Maybe, try it on a diff OS. Maybe make sure you have the latest Docker installed?

Restart your laptop? Sorry, I am running out of ideas now..

**Comment by Os3r3um** [comment]
Have no idea. Will use it as a standalone tool rather than docker. Maybe will find some time and will try it under Arch or Fedora distros.

**Comment by EdOverflow** [comment]
Oh, so sorry! I know what the problem is here. Make sure to comment out this too: https://github.com/EdOverflow/megplus/blob/8d02957ec5a5b3cecd77ecf1768db05767ce2af7/megplus.sh#L65-L68

Note the `exit 1` that is causing the issue.
