### ISSUE TITLE
illegal option -- r and hanging on CRLF tests

### ISSUE THREAD

**Issue by securitybites** [EdOverflow/megplus#14]
## Specifications

- Operating system and version: OSX High Sierra

## Issue details
When running against either a list of hosts or hackerone, MegPlus throws an `illegal option` error while fetching targets. It then hangs on CRLF injection tests. Please see attached image.
![issue](https://user-images.githubusercontent.com/7031736/35938735-146e22e8-0c18-11e8-8a2f-3a7224992bd5.png)

**Comment by EdOverflow** [comment]
Yeah, the `-r` option for sed does not exist on OSX. You have to use the `-E` flag instead.
