### ISSUE TITLE
meg install error

### ISSUE THREAD

**Issue by gwen001** [EdOverflow/megplus#24]
Hi guys,

Following the installation instructions, I get this error:

```
$ go get github.com/tomnomnom/meg
# github.com/tomnomnom/rawhttp
/home/gwen/gocode/src/github.com/tomnomnom/rawhttp/request.go:102: u.Hostname undefined (type *url.URL has no field or method Hostname)
/home/gwen/gocode/src/github.com/tomnomnom/rawhttp/request.go:103: u.Port undefined (type *url.URL has no field or method Port)
/home/gwen/gocode/src/github.com/tomnomnom/rawhttp/request.go:259: undefined: x509.SystemCertPool

```

So meg cannot be installed. Any idea how to solve that?
Thanks :)

**Comment by EdOverflow** [comment]
@TomNomNom, would you be willing to review this for me?

**Comment by tomnomnom** [comment]
Hello! Looks like you're using an old version of Go!

I suggest either upgrading your version of Go, or downloading a binary from the meg releases page https://github.com/tomnomnom/meg/releases

**Comment by gwen001** [comment]
Finally fixed, thanks :)
