### ISSUE TITLE
Error while running the script.

### ISSUE THREAD

**Issue by motherflecker** [EdOverflow/megplus#26]
## Specifications

- Operating system and version:
Ubuntu - 18.04.1 LTS
## Issue details

Running error.

Image attached.

![untitled](https://user-images.githubusercontent.com/44265158/50737934-5d81f080-11f4-11e9-9845-fd091493e352.png)

**Comment by motherflecker** [comment]
@EdOverflow

**Comment by EdOverflow** [comment]
You need to install Python and Sublist3r as stated in https://github.com/EdOverflow/megplus#installation.
