### ISSUE TITLE
sublist3r worked but then

### ISSUE THREAD

**Issue by dirtycoder0124** [EdOverflow/megplus#5]
+] Finding configuration files.
grep: out/: No such file or directory

[+] Finding interesting strings.
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory
grep: out/: No such file or directory

[+] Finding open redirects.
grep: out/: No such file or directory

[+] Finding CRLF injection.

[+] Finding CORS misconfigurations.

**Comment by anshumanbh** [comment]
@dirtycoder0124 the directory from where you are running the docker run command, are you allowed to create directories and writes files? It seems like the `out` directory is not even getting created.

**Comment by dirtycoder0124** [comment]
Yes out directory is not created.
File permissions are
root@kali:~/recon/megplus# ls -ltr
total 44
-rwxrwxrwx 1 root root 1082 Feb  4 10:28 LICENSE
-rwxrwxrwx 1 root root 2641 Feb  4 10:28 README.md
-rwxrwxrwx 1 root root 3921 Feb  4 10:28 megplus.sh
drwxrwxrwx 2 root root 4096 Feb  4 10:28 lists
-rwxrwxrwx 1 root root  750 Feb  4 10:28 findtakeovers.sh
-rwxrwxrwx 1 root root  408 Feb  4 10:28 findstrings.sh
-rwxrwxrwx 1 root root 2374 Feb  4 10:28 fetch.php
-rwxrwxrwx 1 root root 1310 Feb  4 10:28 cors.sh
drwxrwxrwx 4 root root 4096 Feb  4 11:41 Sublist3r
-rwxrwxrwx 1 root root 5734 Feb  4 12:41 domains-meg

**Comment by Chan9390** [comment]
Hey @dirtycoder0124 this happened to me also. The problem was with configuring the paths of dependencies. Check if you have configured the path of `meg` and `waybackurls`.

What's the output of the commands: `which meg` and `which waybackurls` ?

**Comment by dirtycoder0124** [comment]
which command does not show anything

**Comment by d1pakda5** [comment]
Same issue also i am facing

**Comment by EdOverflow** [comment]
@dirtycoder0124, does creating an `out/` folder fix the issue?

**Comment by Erreur32** [comment]
Yes ;) 

$ mkdir out

**Comment by EdOverflow** [comment]
In that case, this should fix everything now:

```
$ git pull
```

**Comment by Chan9390** [comment]
Hey folks, sorry for being late.
From @dirtycoder0124 comment, I can understand that he hasn't added the go compiled binary's path to the path.
So all you have to do is:
1. Check the output of `go env`. Make sure that **`GOPATH`** is set to some path.
   ( In my case `GOPATH="/go"` )
2. Then add that to your environment variable.
   `PATH=$PATH:$GOPATH/bin`

**Comment by EdOverflow** [comment]
@Chan9390, that is definitely the underlying issue here. My workaround should prevent any further GiitHub issues about this problem in the future.

**Comment by dirtycoder0124** [comment]
Hi this is my setting. Whats wrong here.??
root@kali:~# ls
Desktop   Downloads  go       jwtcrack     Music     Pictures
 recon   Videos
root@kali:~# go env
GOARCH="386"
GOBIN="/root/go/bin"
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.9"
GOTOOLDIR="/usr/lib/go-1.9/pkg/tool/linux_386"
GCCGO="gccgo"
GO386="387"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0
-fdebug-prefix-map=/tmp/go-build825802679=/tmp/go-build
-gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
root@kali:~#

**Comment by EdOverflow** [comment]
@dirtycoder0124, please follow the instructions here: https://github.com/EdOverflow/megplus/issues/5#issuecomment-363109169.

**Comment by tomnomnom** [comment]
@dirtycoder0124 what @EdOverflow said :)

Or failing that, [download a binary from the the releases page](https://github.com/tomnomnom/meg/releases/) (e.g. if you're on 64 bit linux it's `meg-linux-amd64-0.2.2.tgz`, if you're on 32 bit linux it's `meg-linux-386-0.2.2.tgz`).

Extract the tarball:

```
▶ tar xvzf meg-linux-amd64-0.2.2.tgz 
meg
```

And move it into your `$PATH`, e.g. in `/usr/bin/`:

```
▶ sudo mv meg /usr/bin/meg
```

**Comment by dirtycoder0124** [comment]
Can anyone please create video tuts to setup megplus. Please Please
